<a href="https://colab.research.google.com/github/ehsankarami1358/ehsan/blob/main/PCA03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from tensorflow.keras.datasets import fashion_mnist
(X_train,y_train),(X_test,y_test)=fashion_mnist.load_data()

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn.decomposition import PCA

In [ ]:
x_train_reshaped=X_train.reshape(X_train.shape[0],-1).astype('float32')
x_test_reshaped=X_test.reshape(X_test.shape[0],-1).astype('float32')
min_max_scaler=MinMaxScaler()
x_train_scaled=min_max_scaler.fit_transform(x_train_reshaped)
x_test_scaled=min_max_scaler.transform(x_test_reshaped)

In [ ]:
pca=PCA(n_components=0.95)
x_train_pca=pca.fit_transform(x_train_scaled)
x_test_pca=pca.transform(x_test_scaled)

In [ ]:
from sklearn.svm import SVC
svc_linear=SVC(kernel='linear',random_state=42)
svc_linear.fit(x_train_pca,y_train)

SVC(kernel='linear', random_state=42)

In [ ]:
y_pred=svc_linear.predict(x_test_pca)
accuracy=accuracy_score(y_test,y_pred)
print(f'Accuracy with PCA:{accuracy}')

Accuracy with PCA:0.8532


In [ ]:

confusion_matrix=confusion_matrix(y_test,y_pred)
print('Confusion Matrix:')
print(confusion_matrix)

Confusion Matrix:
[[827   4  11  43   2   1 100   0  12   0]
 [  5 959   4  26   3   0   2   0   1   0]
 [ 22   4 761  10 119   0  78   0   6   0]
 [ 38  13  14 873  24   0  33   0   5   0]
 [  2   2 110  34 766   0  82   0   4   0]
 [  1   0   0   1   0 930   0  50   2  16]
 [151   1 114  40  91   0 581   0  22   0]
 [  0   0   0   0   0  31   0 948   0  21]
 [  9   2   6   8   4   7  16   3 945   0]
 [  0   0   0   0   0  18   1  39   0 942]]


In [ ]:
from sklearn.model_selection import RandomizedSearchCV
import pandas as pd

In [ ]:
from ast import Param
param_distribution={
    'C':[0.1,1,10],
    'kernel':['linear','rbf','poly'],
    'gamma':['scale','auto']
                   }
n_combinations=len(param_distribution['C'])*len(param_distribution['kernel'])*len(param_distribution['gamma'])
random_search=RandomizedSearchCV(estimator=svc_linear,param_distributions=param_distribution,n_iter=10,cv=5,random_state=42)

In [ ]:
results_df=pd.DataFrame({
    'params':list(random_search.cv_results_['params']),
    'Score':random_search.cv_results_['mean_test_score'],
    'Rank':random_search.cv_results_['rank_test_score']
})
results_df.sort_values(by='rank_test_score',inplace=True)

AttributeError: 'RandomizedSearchCV' object has no attribute 'cv_results_'